### ISSUE TITLE
gif、sprite、animate相关

### ISSUE THREAD

**Issue by 349989153** [349989153/349989153.github.io#24]
sprite转gif：

https://is.si/animator/

**Comment by 349989153** [comment]
sprite动起来的一个例子：

```css
@keyframes hua2-h {
    0% {
        background-position-x: 0px;
    }

    100% {
        background-position-x: -2695px;
    }
}

@keyframes hua2-v {
    0% {
        background-position-y: 0px;
    }

    100% {
        background-position-y: -350px;
    }
}

.sprite-hua2 {
    --dur: 1;
    --col: 11;
    --row: 2;
    background-image: url(assets/hua2.png);
    background-size: 2695px 350px;
    width: 245px;
    height: 175px;
    animation: hua2-h calc((var(--dur) / var(--row)) * 1s) steps(var(--col)) infinite, hua2-v calc(var(--dur) * 1s) steps(var(--row)) infinite;
}
```

![hua2](https://user-images.githubusercontent.com/10381674/187173589-388d2046-5783-4d28-96f2-5be7c724fc84.png)
